all:
		gcc test_json.c ./cJSON/cJSON.c -o test_json -lm
		gcc test_json2.c ./cJSON/cJSON.c -o test_json2 -lm
		gcc test_json3.c ./cJSON/cJSON.c -o test_json3 -lm
		gcc test_json4.c ./cJSON/cJSON.c -o test_json4 -lm
		gcc test_json5.c ./cJSON/cJSON.c -o test_json5 -lm
		gcc test_json6.c ./cJSON/cJSON.c -o test_json6 -lm
clean:
		rm *.o  test_json test_json2 test_json3 test_json4 test_json5 test_json6 -rf